import type { Metadata, Viewport } from "next";
import "./globals.css";
import { Josefin_Sans } from "next/font/google";

// ✅ Fix: must specify viewport meta tag For IOS Devices auto scale when tap on input field.
export const viewport: Viewport = {
  initialScale: 1,
  maximumScale: 1,
  width: "device-width",
};

// ✅ Fix: must specify subsets
const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  variable: "--font-josefin-sans",
});

export const metadata: Metadata = {
  title: "Transport Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

      <html lang="en" className={`${josefinSans.variable}`}>
        <body className="font-body   overflow-x-hidden">
                {children}
        </body>
      </html>
  );
}
